#!/bin/sh
set -eu

cp -a CHANGES.rst tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

export LC_ALL=C.UTF-8
export http_proxy=''

PYTEST_MATCH="not test_main_module_paths"

for py3vers in $(py3versions -s); do
    echo
    echo "***************************"
    echo "*** Testing with ${py3vers}"
    echo "***************************"
    echo
    cd ${AUTOPKGTEST_TMP} && \
        echo "Content of current working folder:\n" && \
        ls -la && \
        echo "Running tests...\n" && \
        PYTHONPATH=. ${py3vers} -m pytest -k "${PYTEST_MATCH}" && \
        rm -rf .pytest_cache || exit 1
done
